name: Build

on:
  pull_request:
    branches:
      - main
      - '!release/**'
  push:
    branches:
      - main
      - '!release/**'

# for a list of available images see https://github.com/actions/runner-images?tab=readme-ov-file#available-images
# for available Xcode versions see https://github.com/actions/runner-images/tree/main/images/macos
env:
  XCODE_APP: ${{ vars.XCODE_VERSION && format('Xcode_{0}.app', vars.XCODE_VERSION) || 'Xcode.app' }}

jobs:
  build:
    name: Build packages
    runs-on: macos-${{ vars.MACOS_VERSION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and cache
        uses: ./.github/actions/nodejs

      - name: Set up Xcode version
        run: sudo xcode-select -switch /Applications/$XCODE_APP

      - name: Build and verify
        run: npm run verify

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
