name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - '!release/**'

env:
  IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
  IS_DBOT: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}

jobs:
  lint:
    name: Lint code
    runs-on: macos-${{ vars.MACOS_VERSION }}
    steps:
      - name: Checkout origin repo
        if: ${{ env.IS_FORK == 'false' && env.IS_DBOT == 'false' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BM_GITHUB_PAT }}
          fetch-depth: 2
      - name: Checkout forked repo
        if: ${{ env.IS_FORK == 'true' || env.IS_DBOT == 'true' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js and cache
        uses: ./.github/actions/nodejs

      - name: Lint-check
        run: npm run lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
